#!/bin/bash

##################################
## ls, exa & more colored stuff ##
##################################

if which exa >/dev/null; then
	# exa is a modern ls replacement with Git integration: https://the.exa.website
  alias ls="exa --git-ignore"
  alias ll="exa --git-ignore --git -l --group"
  alias la="exa --git -la"
else
	alias ls="ls --color=always"
	alias ll="ls -l"
	alias la="ls -lA"
fi
for alias in lsl sls lsls sl l s; do alias $alias=ls; done


###########################
## Other helpful aliases ##
###########################

# To install ag -> https://github.com/ggreer/the_silver_searcher#linux
# If ag is not installed, alias it to "grep -rn" (and generally force color for grep)
alias grep="grep --color=always"
#which rg >/dev/null || alias ag="grep -rn"

# Provide a yq command to use jq with YAML files
# alias yq="python3 -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' | jq"
alias python=python3

# A really simple password generator
alias pw='bash -c '"'"'echo `tr -dc $([ $# -gt 1 ] && echo $2 || echo "A-Za-z0-9") < /dev/urandom | head -c $([ $# -gt 0 ] && echo $1 || echo 30)`'"'"' --'

# Vim Aliases -- Use Neovim
alias vim="nvim"
alias vi="nvim"
alias oldvim="vim"
alias vimdiff='nvim -d'
alias v=vim

